apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: infrawallet
  description: Backstage plugin that shows cloud costs
  tags:
   - node
   - plugin
   - backstage
spec:
  type: website
  owner: user:kadel
  lifecycle: experimental
